FROM __IMAGE__:__TAG__

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential wget \
    && wget https://cmake.org/files/v3.22/cmake-3.22.3-linux-x86_64.sh \
    && chmod +x ./cmake-3.22.3-linux-x86_64.sh \
    && ./cmake-3.22.3-linux-x86_64.sh --skip-license \
    && rm ./cmake-3.22.3-linux-x86_64.sh \
    && apt-get -y autoremove && apt-get -y autoclean && apt-get -y purge wget \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash"]
